"""initial migration.

Revision ID: 69ef37cd6d32
Revises: 
Create Date: 2025-01-30 12:21:55.027520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ef37cd6d32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('causes', sa.JSON(), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('prevention', sa.JSON(), nullable=True),
    sa.Column('treatment', sa.JSON(), nullable=True),
    sa.Column('pathogen', sa.String(length=255), nullable=True),
    sa.Column('mode_of_spread', sa.String(length=255), nullable=True),
    sa.Column('incubation_period', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('usage', sa.Text(), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('precautions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preventive_measures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('preventive_measures')
    op.drop_table('health_tips')
    op.drop_table('drug')
    op.drop_table('diseases')
    # ### end Alembic commands ###
